// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pricecheckingtoolapi.Db;

namespace pricecheckingtoolapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("pricecheckingtoolapi.Models.Currency", b =>
                {
                    b.Property<string>("currencyTypeName")
                        .HasColumnType("varchar(35)")
                        .HasMaxLength(35);

                    b.Property<double>("chaosEquivalent")
                        .HasColumnType("double");

                    b.HasKey("currencyTypeName");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("pricecheckingtoolapi.Models.Item", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("baseType")
                        .HasColumnType("longtext");

                    b.Property<double>("chaosValue")
                        .HasColumnType("double");

                    b.Property<double>("exaltedValue")
                        .HasColumnType("double");

                    b.Property<string>("icon")
                        .HasColumnType("longtext");

                    b.Property<int>("links")
                        .HasColumnType("int");

                    b.Property<int>("mapTier")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("pricecheckingtoolapi.Models.Party", b =>
                {
                    b.Property<int>("partyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("partyId");

                    b.ToTable("Partys");
                });

            modelBuilder.Entity("pricecheckingtoolapi.Models.PartyUser", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("partyId")
                        .HasColumnType("int");

                    b.HasKey("userId", "partyId");

                    b.HasIndex("partyId");

                    b.ToTable("PartyUser");
                });

            modelBuilder.Entity("pricecheckingtoolapi.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("sessionId")
                        .HasColumnType("longtext");

                    b.HasKey("userId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("pricecheckingtoolapi.Models.PartyUser", b =>
                {
                    b.HasOne("pricecheckingtoolapi.Models.Party", "party")
                        .WithMany("partyUser")
                        .HasForeignKey("partyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pricecheckingtoolapi.Models.User", "user")
                        .WithMany("partyUser")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
